apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: carltest
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /
  storage:
    type: memory
  ingress:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"